version: '3'
services:
  web:
    restart: always
    image: 127.0.0.1:5000/shake-web
    build: ./repos/Armory
    environment:
      - DB=${DB_CONFIG}
      - SECRET=thisissecretforproduction
      - SUPER_ADMIN_TOKEN=12345
      - PORT=7000
    ports:
      - 7000:7000

  rank:
    restart: always
    image: 127.0.0.1:5000/shake-rank
    build: ./repos/Barracks
    environment:
      - DB=${DB_GO_CONFIG}
      - PORT=8000
      - CONTEST=contest01
      - PUSHHOST=localhost:8000

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=armory-production
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  router:
    image: nginx:latest

  dashboard:
    image: charypar/swarm-dashboard
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    environment:
      PORT: 8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager