version: '3'
services:
  web:
    restart: always
    image: 127.0.0.1:5000/shake-web
    build: ./repos/Armory
    environment:
      - DB=${DB_CONFIG}
      - SECRET=thisissecretforproduction
      - SUPER_ADMIN_TOKEN=12345
      - PORT=7000
      - RANK_HOST=http://rank:7001
    ports:
      - 7000:7000

  rank:
    restart: always
    image: 127.0.0.1:5000/shake-rank
    build: ./repos/Barracks
    environment:
      - DB=${DB_GO_CONFIG}
      - PORT=7001
      - CONTEST=contest01
      - PUSHHOST=web:7000
    ports:
      - 7001:7001

  router:
    image: nginx:latest

  dashboard:
    image: charypar/swarm-dashboard
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    environment:
      PORT: 8080
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager